CREATE OR ALTER TRIGGER art_id_autoinc FOR ARTISTS
ACTIVE BEFORE INSERT POSITION 0
AS
DECLARE VARIABLE NEW_ID INTEGER;
BEGIN
    SELECT MAX(ART_ID) FROM ARTISTS INTO :NEW_ID;
    NEW.ART_ID = :NEW_ID + 1;
END
-- Завершение транзакции
COMMIT;