CREATE OR ALTER TRIGGER AWARD_CTL FOR AWARDS
ACTIVE BEFORE DELETE POSITION 0
AS
BEGIN
    DELETE FROM ALB_AWARDS WHERE ALB_AWARDS.AWARD_ID = OLD.AWARD_ID;
    DELETE FROM TRACK_AWARDS WHERE TRACK_AWARDS.AWARD_ID = OLD.AWARD_ID;
END
-- Завершение транзакции
COMMIT;