CREATE OR ALTER TRIGGER pl_not_copy FOR PL_CONTENT
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.TRACK_ID IN (SELECT TRACK_ID FROM PL_CONTENT WHERE PL_ID = NEW.PL_ID)) THEN EXCEPTION ISCOPY;
END