CREATE OR ALTER TRIGGER trk_not_copy FOR TRACKLISTS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.TRACK_ID IN (SELECT TRACK_ID FROM TRACKLISTS WHERE ALB_ID = NEW.ALB_ID)) THEN EXCEPTION ISCOPY;
END
-- Завершение транзакции
COMMIT;