-- Удаление записей, на которые не ссылаются подчиненные таблицы
CREATE OR ALTER PROCEDURE t12 AS
BEGIN
    INSERT INTO TRACKS VALUES ((SELECT MAX(TRACK_ID) FROM TRACKS)+1, 1, 'TEST', '23:59:59');
    DELETE FROM TRACKS WHERE TRACK_ID IN (
        SELECT TRACK_ID FROM TRACKS
            WHERE TRACK_ID NOT IN(SELECT TRACK_ID FROM TRACKLISTS)
            AND TRACK_ID NOT IN(SELECT TRACK_ID FROM PL_CONTENT)
            AND TRACK_ID NOT IN(SELECT TRACK_ID FROM TRACK_AWARDS));
END
-- Завершение транзакции
COMMIT;