-- Объединение таблиц TRACKS и ARTISTS
CREATE OR ALTER VIEW t6_1(TRACK_ID, ART_ID, TITLE, DURATION, ART_ID1, ARTIST) AS
SELECT * FROM TRACKS
    JOIN ARTISTS ON TRACKS.ART_ID = ARTISTS.ART_ID
    ORDER BY TRACK_ID ASC;
-- Подстановка реальных данных вместо внешних ключей в таблицу TRACKLISTS
CREATE OR ALTER VIEW t6_2 AS
SELECT TRACKLISTS.TRKLST_ID, ALBUMS.ALBUM, TRACKS.TITLE FROM TRACKLISTS
    JOIN ALBUMS ON ALBUMS.ALB_ID = TRACKLISTS.ALB_ID
    JOIN TRACKS ON TRACKS.TRACK_ID = TRACKLISTS.TRACK_ID;
-- Завершение транзакции
COMMIT;