-- Выборка артистов, которым принадлежит менее 4300 треков
CREATE OR ALTER VIEW t7(ARTIST, "COUNT") AS
SELECT  ARTISTS.ARTIST, COUNT(TRACKS.ART_ID) FROM TRACKS
    JOIN ARTISTS ON ARTISTS.ART_ID = TRACKS.ART_ID
    GROUP BY ARTISTS.ARTIST HAVING COUNT(TRACKS.ART_ID)<4300;
-- Завершение транзакции
COMMIT;