CREATE OR ALTER VIEW ind1(LABEL, "COUNT") AS
SELECT FIRST 5 LABELS.LABEL, COUNT(LABELS.LABEL_ID) FROM PL_CONTENT
    JOIN TRACKLISTS ON TRACKLISTS.TRACK_ID = PL_CONTENT.TRACK_ID
    JOIN ALBUMS ON TRACKLISTS.ALB_ID = ALBUMS.ALB_ID
    JOIN LABELS ON LABELS.LABEL_ID = ALBUMS.LABEL_ID
    GROUP BY LABELS.LABEL
    ORDER BY COUNT(LABELS.LABEL) DESC;
-- Завершение транзакции
COMMIT;