CREATE OR ALTER VIEW ind2v AS
SELECT TRACKLISTS.TRACK_ID, TRACKS.TITLE FROM TRACKLISTS
    JOIN TRACKS ON TRACKS.TRACK_ID = TRACKLISTS.TRACK_ID
    WHERE ALB_ID IN (
        SELECT ALB_ID FROM ALB_GENRES WHERE GENRE_ID IN (
            SELECT GENRE_ID FROM GENRES WHERE GENRE IN ('Rave'))) OR
    ALB_ID IN (
        SELECT ALB_ID FROM ALBUMS WHERE LABEL_ID IN (
            SELECT LABEL_ID FROM LABELS WHERE LABEL IN ('Unknown Label')))
    GROUP BY TRACKLISTS.TRACK_ID, TRACKS.TITLE
    ORDER BY TRACKLISTS.TRACK_ID ASC;
-- Завершение транзакции
COMMIT;