CREATE OR ALTER PROCEDURE ind2(
    GENRE VARCHAR(40),
    LABEL VARCHAR(100)
)
RETURNS(
    ID INTEGER,
    TITLE VARCHAR(100)
)
AS
BEGIN
    FOR SELECT TRACKLISTS.TRACK_ID, TRACKS.TITLE FROM TRACKLISTS
        JOIN TRACKS ON TRACKS.TRACK_ID = TRACKLISTS.TRACK_ID
        WHERE ALB_ID IN (
            SELECT ALB_ID FROM ALB_GENRES WHERE GENRE_ID IN (
                SELECT GENRE_ID FROM GENRES WHERE GENRE IN (:GENRE))) OR
        ALB_ID IN (
            SELECT ALB_ID FROM ALBUMS WHERE LABEL_ID IN (
                SELECT LABEL_ID FROM LABELS WHERE LABEL IN (:LABEL)))
        GROUP BY TRACKLISTS.TRACK_ID, TRACKS.TITLE
        ORDER BY TRACKLISTS.TRACK_ID ASC
        INTO :ID, :TITLE
    DO
    BEGIN
        SUSPEND;
    END
END
-- Завершение транзакции
COMMIT;