CREATE OR ALTER VIEW ind3 AS
SELECT GENRES.GENRE, (CAST(TRK AS FLOAT)/NULLIF(CAST(ALB AS FLOAT), 0)) AS RATIO FROM GENRES
JOIN (
    SELECT ALB_GENRES.GENRE_ID, COUNT(PL_CONTENT.TRACK_ID) AS TRK FROM PL_CONTENT
        JOIN TRACKLISTS ON TRACKLISTS.TRACK_ID = PL_CONTENT.TRACK_ID
        RIGHT JOIN ALB_GENRES ON TRACKLISTS.ALB_ID = ALB_GENRES.ALB_ID
        GROUP BY ALB_GENRES.GENRE_ID)
    NUM ON NUM.GENRE_ID = GENRES.GENRE_ID
JOIN (
    SELECT GENRE_ID, COUNT(ALB_ID) AS ALB FROM ALB_GENRES
        GROUP BY GENRE_ID)
    DENOM ON DENOM.GENRE_ID = GENRES.GENRE_ID
ORDER BY GENRES.GENRE_ID ASC;
-- Завершение транзакции
COMMIT;