CREATE TABLE SOLD_DAY_SUMMARY (
    SUMMARY_DATE DATE    NOT NULL,
    SOLD_SUM     INTEGER NOT NULL
);

CREATE TABLE SOLD_WEEK_SUMMARY (
    START_DATE  DATE    NOT NULL,
    FINISH_DATE DATE    NOT NULL,
    SOLD_SUM    INTEGER NOT NULL
);

CREATE TABLE SOLD_MONTH_SUMMARY (
    START_DATE  DATE    NOT NULL,
    FINISH_DATE DATE    NOT NULL,
    SOLD_SUM    INTEGER NOT NULL
);

CREATE TABLE SOLD_YEAR_SUMMARY (
    START_DATE  DATE    NOT NULL,
    FINISH_DATE DATE    NOT NULL,
    SOLD_SUM    INTEGER NOT NULL
);

CREATE TABLE SOLD_CITY_SUMMARY (
    CITY_ID  INTEGER NOT NULL,
    SOLD_SUM INTEGER NOT NULL
);

CREATE TABLE SOLD_COUNTRY_SUMMARY (
    COUNTRY_ID INTEGER NOT NULL,
    SOLD_SUM   INTEGER NOT NULL
);

ALTER TABLE SOLD_CITY_SUMMARY
    ADD FOREIGN KEY (CITY_ID) REFERENCES CITY_LIST (CITY_ID);
ALTER TABLE SOLD_COUNTRY_SUMMARY
    ADD FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY_LIST (COUNTRY_ID);
-- Завершение транзакции
COMMIT;